# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 877eac247e2e7f716507dc8a35c4b38da5b0ea9f057b63160c2111fa2f185b913c560f53350e7d9e45591c6e52e13689a8d166a66163ec68a512beec1102fad0

test:
  secret_key_base: e4516838a04654106da111087430fe266f7ae266c01cfed2afe5c9c3b02860815e9c4204cb422e7ca8817d02a9ff8ab2c04d950ffdeee85fce707e14e4fd9ba5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
